import type { MenuItem, ProductCategory } from "@/lib/types"

export const categories: ProductCategory[] = [
  { id: "1", name: "Hot Drinks" },
  { id: "2", name: "Cold Drinks" },
  { id: "3", name: "Pastries" },
  { id: "4", name: "Sandwiches" },
  { id: "5", name: "Desserts" },
]

export const menuItems: MenuItem[] = [
  {
    id: "101",
    name: "Cappuccino",
    price: 4.5,
    categoryId: "1",
    image: "/images/cappuccino.jpg",
    description: "Espresso with steamed milk and a deep layer of foam",
    variants: [
      { id: "v1", name: "Small", price: 0 },
      { id: "v2", name: "Medium", price: 0.5 },
      { id: "v3", name: "Large", price: 1.0 },
    ],
  },
  {
    id: "102",
    name: "Latte",
    price: 4.0,
    categoryId: "1",
    image: "/images/latte.jpg",
    description: "Espresso with steamed milk and a light layer of foam",
    variants: [
      { id: "v1", name: "Small", price: 0 },
      { id: "v2", name: "Medium", price: 0.5 },
      { id: "v3", name: "Large", price: 1.0 },
    ],
  },
  {
    id: "103",
    name: "Espresso",
    price: 3.0,
    categoryId: "1",
    image: "/images/espresso.jpg",
    description: "Concentrated coffee served in a small, strong shot",
    variants: [
      { id: "v1", name: "Single", price: 0 },
      { id: "v2", name: "Double", price: 1.5 },
    ],
  },
  {
    id: "201",
    name: "Iced Coffee",
    price: 4.5,
    categoryId: "2",
    image: "/images/iced-coffee.jpg",
    description: "Chilled coffee served with ice and optional milk",
    variants: [
      { id: "v1", name: "Small", price: 0 },
      { id: "v2", name: "Medium", price: 0.5 },
      { id: "v3", name: "Large", price: 1.0 },
    ],
  },
  {
    id: "202",
    name: "Iced Tea",
    price: 3.5,
    categoryId: "2",
    image: "/images/iced-tea.jpg",
    description: "Refreshing tea served cold with ice",
    variants: [
      { id: "v1", name: "Small", price: 0 },
      { id: "v2", name: "Medium", price: 0.5 },
      { id: "v3", name: "Large", price: 1.0 },
    ],
  },
  {
    id: "203",
    name: "Fruit Smoothie",
    price: 5.5,
    categoryId: "2",
    image: "/images/fruit-smoothie.jpg",
    description: "Blended fresh fruits with yogurt and ice",
    variants: [
      { id: "v1", name: "Strawberry", price: 0 },
      { id: "v2", name: "Mango", price: 0 },
      { id: "v3", name: "Mixed Berry", price: 0.5 },
    ],
  },
  {
    id: "301",
    name: "Croissant",
    price: 3.5,
    categoryId: "3",
    image: "/images/croissant.jpg",
    description: "Buttery, flaky pastry with a golden crust",
  },
  {
    id: "302",
    name: "Pain au Chocolat",
    price: 4.0,
    categoryId: "3",
    image: "/images/pain-au-chocolat.jpg",
    description: "Chocolate-filled croissant pastry",
  },
  {
    id: "303",
    name: "Almond Croissant",
    price: 4.5,
    categoryId: "3",
    image: "/images/almond-croissant.jpg",
    description: "Croissant filled with almond cream and topped with sliced almonds",
  },
  {
    id: "401",
    name: "Chicken Sandwich",
    price: 6.5,
    categoryId: "4",
    image: "/images/chicken-sandwich.jpg",
    description: "Grilled chicken with lettuce, tomato, and mayo on artisan bread",
  },
  {
    id: "402",
    name: "Veggie Sandwich",
    price: 5.5,
    categoryId: "4",
    image: "/images/veggie-sandwich.jpg",
    description: "Fresh vegetables with hummus on whole grain bread",
  },
  {
    id: "403",
    name: "Turkey Club",
    price: 7.5,
    categoryId: "4",
    image: "/images/turkey-club.jpg",
    description: "Turkey, bacon, lettuce, tomato, and mayo on toasted bread",
  },
  {
    id: "501",
    name: "Chocolate Cake",
    price: 5.0,
    categoryId: "5",
    image: "/images/chocolate-cake.jpg",
    description: "Rich chocolate cake with chocolate ganache",
  },
  {
    id: "502",
    name: "Cheesecake",
    price: 5.5,
    categoryId: "5",
    image: "/images/cheesecake.jpg",
    description: "Creamy cheesecake with a graham cracker crust",
  },
  {
    id: "503",
    name: "Tiramisu",
    price: 6.0,
    categoryId: "5",
    image: "/images/tiramisu.jpg",
    description: "Italian dessert with coffee-soaked ladyfingers and mascarpone cream",
  },
]

